import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { TeacherProvider } from "../context/TeacherContext";
import SecurityLayer from "@/components/SecurityLayer";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TeacherProvider>
          {/* <SecurityLayer /> */}
          <Toaster position="top-center" />
          <Navbar />
          <main className="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8 pt-20">
            {children}
          </main>
        </TeacherProvider>
      </body>
    </html>
  );
}
